name: login_page
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.13.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 1.0.4
  firebase_auth:
  flutter_login_facebook:
  auto_size_text: 2.1.0
  http: 0.13.3
  webview_flutter: 2.0.13
  cached_network_image: ^2.2.0+1
  introduction_screen: ^1.0.8
  sleek_circular_slider: ^1.1.0
  rounded_loading_button: ^1.0.0
  animated_text_kit: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: 19.3.45

dev_dependencies:
   flutter_test:
    sdk: flutter

   flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo_background.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
     - assets/facebook-logo-png-2320.png
     - assets/survey.png
     - assets/scan.png
     - assets/background.png
     - assets/exercise.png
     - assets/kcal.png
     - assets/progress.png
     - assets/recipe.png
     - assets/sedentary.png
     - assets/workout1.png
     - assets/workout2.png
     - assets/workout3.png
     - assets/moderate.png
     - assets/high.png
     - assets/light.png
     - assets/artboard4.png


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Trueno , Helvetica , Brandon Grotesque

      fonts:
        - asset: fonts/TruenoExBd.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
